#include <DefaultMessageTypes.h>

const char* k_raknet_packet_id_strings[] = 
{
  "RakNet Packet: ID_CONNECTED_PING",  
  "RakNet Packet: ID_UNCONNECTED_PING",
  "RakNet Packet: ID_UNCONNECTED_PING_OPEN_CONNECTIONS",
  "RakNet Packet: ID_CONNECTED_PONG",
  "RakNet Packet: ID_DETECT_LOST_CONNECTIONS",
  "RakNet Packet: ID_OPEN_CONNECTION_REQUEST_1",
  "RakNet Packet: ID_OPEN_CONNECTION_REPLY_1",
  "RakNet Packet: ID_OPEN_CONNECTION_REQUEST_2",
  "RakNet Packet: ID_OPEN_CONNECTION_REPLY_2",
  "RakNet Packet: ID_CONNECTION_REQUEST",
  "RakNet Packet: ID_REMOTE_SYSTEM_REQUIRES_PUBLIC_KEY",
  "RakNet Packet: ID_OUR_SYSTEM_REQUIRES_SECURITY",
  "RakNet Packet: ID_PUBLIC_KEY_MISMATCH",
  "RakNet Packet: ID_OUT_OF_BAND_INTERNAL",
  "RakNet Packet: ID_SND_RECEIPT_ACKED",
  "RakNet Packet: ID_SND_RECEIPT_LOSS",
  "RakNet Packet: ID_CONNECTION_REQUEST_ACCEPTED",
  "RakNet Packet: ID_CONNECTION_ATTEMPT_FAILED",
  "RakNet Packet: ID_ALREADY_CONNECTED",
  "RakNet Packet: ID_NEW_INCOMING_CONNECTION",
  "RakNet Packet: ID_NO_FREE_INCOMING_CONNECTIONS",
  "RakNet Packet: ID_DISCONNECTION_NOTIFICATION",
  "RakNet Packet: ID_CONNECTION_LOST",
  "RakNet Packet: ID_CONNECTION_BANNED",
  "RakNet Packet: ID_INVALID_PASSWORD",
  "RakNet Packet: ID_INCOMPATIBLE_PROTOCOL_VERSION",
  "RakNet Packet: ID_IP_RECENTLY_CONNECTED",
  "RakNet Packet: ID_TIMESTAMP",
  "RakNet Packet: ID_UNCONNECTED_PONG",
  "RakNet Packet: ID_ADVERTISE_SYSTEM",
  "RakNet Packet: ID_DOWNLOAD_PROGRESS",
  "RakNet Packet: ID_REMOTE_DISCONNECTION_NOTIFICATION",
  "RakNet Packet: ID_REMOTE_CONNECTION_LOST",
  "RakNet Packet: ID_REMOTE_NEW_INCOMING_CONNECTION",
  "RakNet Packet: ID_FILE_LIST_TRANSFER_HEADER",
  "RakNet Packet: ID_FILE_LIST_TRANSFER_FILE",
  "RakNet Packet: ID_FILE_LIST_REFERENCE_PUSH_ACK",
  "RakNet Packet: ID_DDT_DOWNLOAD_REQUEST",
  "RakNet Packet: ID_TRANSPORT_STRING",
  "RakNet Packet: ID_REPLICA_MANAGER_CONSTRUCTION",
  "RakNet Packet: ID_REPLICA_MANAGER_SCOPE_CHANGE",
  "RakNet Packet: ID_REPLICA_MANAGER_SERIALIZE",
  "RakNet Packet: ID_REPLICA_MANAGER_DOWNLOAD_STARTED",
  "RakNet Packet: ID_REPLICA_MANAGER_DOWNLOAD_COMPLETE",
  "RakNet Packet: ID_RAKVOICE_OPEN_CHANNEL_REQUEST",
  "RakNet Packet: ID_RAKVOICE_OPEN_CHANNEL_REPLY",
  "RakNet Packet: ID_RAKVOICE_CLOSE_CHANNEL",
  "RakNet Packet: ID_RAKVOICE_DATA",
  "RakNet Packet: ID_AUTOPATCHER_GET_CHANGELIST_SINCE_DATE",
  "RakNet Packet: ID_AUTOPATCHER_CREATION_LIST",
  "RakNet Packet: ID_AUTOPATCHER_DELETION_LIST",
  "RakNet Packet: ID_AUTOPATCHER_GET_PATCH",
  "RakNet Packet: ID_AUTOPATCHER_PATCH_LIST",
  "RakNet Packet: ID_AUTOPATCHER_REPOSITORY_FATAL_ERROR",
  "RakNet Packet: ID_AUTOPATCHER_CANNOT_DOWNLOAD_ORIGINAL_UNMODIFIED_FILES",
  "RakNet Packet: ID_AUTOPATCHER_FINISHED_INTERNAL",
  "RakNet Packet: ID_AUTOPATCHER_FINISHED",
  "RakNet Packet: ID_AUTOPATCHER_RESTART_APPLICATION",
  "RakNet Packet: ID_NAT_PUNCHTHROUGH_REQUEST",
  "RakNet Packet: ID_NAT_CONNECT_AT_TIME",
  "RakNet Packet: ID_NAT_GET_MOST_RECENT_PORT",
  "RakNet Packet: ID_NAT_CLIENT_READY",
  "RakNet Packet: ID_NAT_TARGET_NOT_CONNECTED",
  "RakNet Packet: ID_NAT_TARGET_UNRESPONSIVE",
  "RakNet Packet: ID_NAT_CONNECTION_TO_TARGET_LOST",
  "RakNet Packet: ID_NAT_ALREADY_IN_PROGRESS",
  "RakNet Packet: ID_NAT_PUNCHTHROUGH_FAILED",
  "RakNet Packet: ID_NAT_PUNCHTHROUGH_SUCCEEDED",
  "RakNet Packet: ID_READY_EVENT_SET",
  "RakNet Packet: ID_READY_EVENT_UNSET",
  "RakNet Packet: ID_READY_EVENT_ALL_SET",
  "RakNet Packet: ID_READY_EVENT_QUERY",
  "RakNet Packet: ID_LOBBY_GENERAL",
  "RakNet Packet: ID_RPC_REMOTE_ERROR",
  "RakNet Packet: ID_RPC_PLUGIN",
  "RakNet Packet: ID_FILE_LIST_REFERENCE_PUSH",
  "RakNet Packet: ID_READY_EVENT_FORCE_ALL_SET",
  "RakNet Packet: ID_ROOMS_EXECUTE_FUNC",
  "RakNet Packet: ID_ROOMS_LOGON_STATUS",
  "RakNet Packet: ID_ROOMS_HANDLE_CHANGE",
  "RakNet Packet: ID_LOBBY2_SEND_MESSAGE",
  "RakNet Packet: ID_LOBBY2_SERVER_ERROR",
  "RakNet Packet: ID_FCM2_NEW_HOST",
  "RakNet Packet: ID_FCM2_REQUEST_FCMGUID",
  "RakNet Packet: ID_FCM2_RESPOND_CONNECTION_COUNT",
  "RakNet Packet: ID_FCM2_INFORM_FCMGUID",
  "RakNet Packet: ID_FCM2_UPDATE_MIN_TOTAL_CONNECTION_COUNT",
  "RakNet Packet: ID_FCM2_VERIFIED_JOIN_START",
  "RakNet Packet: ID_FCM2_VERIFIED_JOIN_CAPABLE",
  "RakNet Packet: ID_FCM2_VERIFIED_JOIN_FAILED",
  "RakNet Packet: ID_FCM2_VERIFIED_JOIN_ACCEPTED",
  "RakNet Packet: ID_FCM2_VERIFIED_JOIN_REJECTED",
  "RakNet Packet: ID_UDP_PROXY_GENERAL",
  "RakNet Packet: ID_SQLite3_EXEC",
  "RakNet Packet: ID_SQLite3_UNKNOWN_DB",
  "RakNet Packet: ID_SQLLITE_LOGGER",
  "RakNet Packet: ID_NAT_TYPE_DETECTION_REQUEST",
  "RakNet Packet: ID_NAT_TYPE_DETECTION_RESULT",
  "RakNet Packet: ID_ROUTER_2_INTERNAL",
  "RakNet Packet: ID_ROUTER_2_FORWARDING_NO_PATH",
  "RakNet Packet: ID_ROUTER_2_FORWARDING_ESTABLISHED",
  "RakNet Packet: ID_ROUTER_2_REROUTED",
  "RakNet Packet: ID_TEAM_BALANCER_INTERNAL",
  "RakNet Packet: ID_TEAM_BALANCER_REQUESTED_TEAM_FULL",
  "RakNet Packet: ID_TEAM_BALANCER_REQUESTED_TEAM_LOCKED",
  "RakNet Packet: ID_TEAM_BALANCER_TEAM_REQUESTED_CANCELLED",
  "RakNet Packet: ID_TEAM_BALANCER_TEAM_ASSIGNED",
  "RakNet Packet: ID_LIGHTSPEED_INTEGRATION",
  "RakNet Packet: ID_XBOX_LOBBY",
  "RakNet Packet: ID_TWO_WAY_AUTHENTICATION_INCOMING_CHALLENGE_SUCCESS",
  "RakNet Packet: ID_TWO_WAY_AUTHENTICATION_OUTGOING_CHALLENGE_SUCCESS",
  "RakNet Packet: ID_TWO_WAY_AUTHENTICATION_INCOMING_CHALLENGE_FAILURE",
  "RakNet Packet: ID_TWO_WAY_AUTHENTICATION_OUTGOING_CHALLENGE_FAILURE",
  "RakNet Packet: ID_TWO_WAY_AUTHENTICATION_OUTGOING_CHALLENGE_TIMEOUT",
  "RakNet Packet: ID_TWO_WAY_AUTHENTICATION_NEGOTIATION",
  "RakNet Packet: ID_CLOUD_POST_REQUEST",
  "RakNet Packet: ID_CLOUD_RELEASE_REQUEST",
  "RakNet Packet: ID_CLOUD_GET_REQUEST",
  "RakNet Packet: ID_CLOUD_GET_RESPONSE",
  "RakNet Packet: ID_CLOUD_UNSUBSCRIBE_REQUEST",
  "RakNet Packet: ID_CLOUD_SERVER_TO_SERVER_COMMAND",
  "RakNet Packet: ID_CLOUD_SUBSCRIPTION_NOTIFICATION",
  "RakNet Packet: ID_LIB_VOICE",
  "RakNet Packet: ID_RELAY_PLUGIN",
  "RakNet Packet: ID_NAT_REQUEST_BOUND_ADDRESSES",
  "RakNet Packet: ID_NAT_RESPOND_BOUND_ADDRESSES",
  "RakNet Packet: ID_FCM2_UPDATE_USER_CONTEXT",
  "RakNet Packet: ID_RESERVED_3",
  "RakNet Packet: ID_RESERVED_4",
  "RakNet Packet: ID_RESERVED_5",
  "RakNet Packet: ID_RESERVED_6",
  "RakNet Packet: ID_RESERVED_7",
  "RakNet Packet: ID_RESERVED_8",
  "RakNet Packet: ID_RESERVED_9",
  "RakNet Packet: ID_USER_PACKET_ENUM"
};

//StartupResult
const char* k_startup_result_string[] =
{
  "ClientStartup Result: RAKNET_STARTED",
  "ClientStartup Result: RAKNET_ALREADY_STARTED",
  "ClientStartup Result: INVALID_SOCKET_DESCRIPTORS",
  "ClientStartup Result: INVALID_MAX_CONNECTIONS",
  "ClientStartup Result: SOCKET_FAMILY_NOT_SUPPORTED",
  "ClientStartup Result: SOCKET_PORT_ALREADY_IN_USE",
  "ClientStartup Result: SOCKET_FAILED_TO_BIND",
  "ClientStartup Result: SOCKET_FAILED_TEST_SEND",
  "ClientStartup Result: PORT_CANNOT_BE_ZERO",
  "ClientStartup Result: FAILED_TO_CREATE_NETWORK_THREAD",
  "ClientStartup Result: COULD_NOT_GENERATE_GUID",
  "ClientStartup Result: STARTUP_OTHER_FAILURE"
};

//ConnectionAttemptResult
const char* k_connection_result_string[] =
{
  "Connection Result: CONNECTION_ATTEMPT_STARTED",
  "Connection Result: INVALID_PARAMETER",
  "Connection Result: CANNOT_RESOLVE_DOMAIN_NAME",
  "Connection Result: ALREADY_CONNECTED_TO_ENDPOINT",
  "Connection Result: CONNECTION_ATTEMPT_ALREADY_IN_PROGRESS",
  "Connection Result: SECURITY_INITIALIZATION_FAILED"
};

//ConnectionState
const char* k_connection_state_result_string[] =
{
  "ConnectionState Result: Connect() was called, but the process hasn't started yet",
  "ConnectionState Result: Processing the connection attempt",
  "ConnectionState Result: Is connected and able to communicate",
  "ConnectionState Result: Was connected, but will disconnect as soon as the remaining messages are delivered",
  "ConnectionState Result: A connection attempt failed and will be aborted",
  "ConnectionState Result: No longer connected",
  "ConnectionState Result: Was never connected, or else was disconnected long enough ago that the entry has been discarded"
};