//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: RProto.proto
namespace rproto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChatMessage")]
  public partial class ChatMessage : global::ProtoBuf.IExtensible
  {
    public ChatMessage() {}
    
    private string _owner_ip = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"owner_ip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string owner_ip
    {
      get { return _owner_ip; }
      set { _owner_ip = value; }
    }
    private string _owner_name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"owner_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string owner_name
    {
      get { return _owner_name; }
      set { _owner_name = value; }
    }
    private rproto.ChatMessage.ChatType _msg_type = rproto.ChatMessage.ChatType.chat_null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"msg_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(rproto.ChatMessage.ChatType.chat_null)]
    public rproto.ChatMessage.ChatType msg_type
    {
      get { return _msg_type; }
      set { _msg_type = value; }
    }
    private string _content = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string content
    {
      get { return _content; }
      set { _content = value; }
    }
    private string _reciever_name = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"reciever_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string reciever_name
    {
      get { return _reciever_name; }
      set { _reciever_name = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ChatType")]
    public enum ChatType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"chat_null", Value=0)]
      chat_null = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"chat_normal", Value=1)]
      chat_normal = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"chat_whisper", Value=2)]
      chat_whisper = 2
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GameNotice")]
  public partial class GameNotice : global::ProtoBuf.IExtensible
  {
    public GameNotice() {}
    
    private rproto.GameNotice.NoticeType _msg_type = rproto.GameNotice.NoticeType.m_null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"msg_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(rproto.GameNotice.NoticeType.m_null)]
    public rproto.GameNotice.NoticeType msg_type
    {
      get { return _msg_type; }
      set { _msg_type = value; }
    }
    private string _content = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string content
    {
      get { return _content; }
      set { _content = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"NoticeType")]
    public enum NoticeType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"m_null", Value=0)]
      m_null = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"m_normal", Value=1)]
      m_normal = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"m_error", Value=2)]
      m_error = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"m_notice", Value=3)]
      m_notice = 3
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RMsg")]
  public partial class RMsg : global::ProtoBuf.IExtensible
  {
    public RMsg() {}
    
    private rproto.RMessageType _message_id = rproto.RMessageType.msg_null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"message_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(rproto.RMessageType.msg_null)]
    public rproto.RMessageType message_id
    {
      get { return _message_id; }
      set { _message_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SRequest")]
  public partial class SRequest : global::ProtoBuf.IExtensible
  {
    public SRequest() {}
    
    private rproto.SRequest.RequestType _request_id = rproto.SRequest.RequestType.r_null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"request_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(rproto.SRequest.RequestType.r_null)]
    public rproto.SRequest.RequestType request_id
    {
      get { return _request_id; }
      set { _request_id = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"RequestType")]
    public enum RequestType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"r_null", Value=0)]
      r_null = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"r_pinfo", Value=1)]
      r_pinfo = 1
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CRequest")]
  public partial class CRequest : global::ProtoBuf.IExtensible
  {
    public CRequest() {}
    
    private rproto.CRequest.RequestType _request_id = rproto.CRequest.RequestType.r_null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"request_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(rproto.CRequest.RequestType.r_null)]
    public rproto.CRequest.RequestType request_id
    {
      get { return _request_id; }
      set { _request_id = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"RequestType")]
    public enum RequestType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"r_null", Value=0)]
      r_null = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"r_pinfo", Value=1)]
      r_pinfo = 1
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerInfo")]
  public partial class PlayerInfo : global::ProtoBuf.IExtensible
  {
    public PlayerInfo() {}
    
    private string _name = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private string _ip = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"ip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ip
    {
      get { return _ip; }
      set { _ip = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TestMessage")]
  public partial class TestMessage : global::ProtoBuf.IExtensible
  {
    public TestMessage() {}
    
    private string _data = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string data
    {
      get { return _data; }
      set { _data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Ent")]
  public partial class Ent : global::ProtoBuf.IExtensible
  {
    public Ent() {}
    
    private int _type_id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"type_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int type_id
    {
      get { return _type_id; }
      set { _type_id = value; }
    }
    private int _game_id = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"game_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int game_id
    {
      get { return _game_id; }
      set { _game_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Cell")]
  public partial class Cell : global::ProtoBuf.IExtensible
  {
    public Cell() {}
    
    private int _cx = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"cx", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int cx
    {
      get { return _cx; }
      set { _cx = value; }
    }
    private int _cy = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cy", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int cy
    {
      get { return _cy; }
      set { _cy = value; }
    }
    private readonly global::System.Collections.Generic.List<rproto.Ent> _ents = new global::System.Collections.Generic.List<rproto.Ent>();
    [global::ProtoBuf.ProtoMember(3, Name=@"ents", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<rproto.Ent> ents
    {
      get { return _ents; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"View")]
  public partial class View : global::ProtoBuf.IExtensible
  {
    public View() {}
    
    private int _radius = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"radius", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int radius
    {
      get { return _radius; }
      set { _radius = value; }
    }
    private readonly global::System.Collections.Generic.List<rproto.Cell> _cells = new global::System.Collections.Generic.List<rproto.Cell>();
    [global::ProtoBuf.ProtoMember(2, Name=@"cells", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<rproto.Cell> cells
    {
      get { return _cells; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerMoveCommand")]
  public partial class PlayerMoveCommand : global::ProtoBuf.IExtensible
  {
    public PlayerMoveCommand() {}
    
    private float _dx = default(float);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"dx", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float dx
    {
      get { return _dx; }
      set { _dx = value; }
    }
    private float _dy = default(float);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"dy", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float dy
    {
      get { return _dy; }
      set { _dy = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerPos")]
  public partial class PlayerPos : global::ProtoBuf.IExtensible
  {
    public PlayerPos() {}
    
    private float _px = default(float);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"px", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float px
    {
      get { return _px; }
      set { _px = value; }
    }
    private float _py = default(float);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"py", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float py
    {
      get { return _py; }
      set { _py = value; }
    }
    private int _cx = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"cx", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int cx
    {
      get { return _cx; }
      set { _cx = value; }
    }
    private int _cy = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"cy", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int cy
    {
      get { return _cy; }
      set { _cy = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"RMessageType")]
    public enum RMessageType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"msg_null", Value=0)]
      msg_null = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"msg_shutdown_server", Value=1)]
      msg_shutdown_server = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"msg_chat", Value=2)]
      msg_chat = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"msg_player_info", Value=3)]
      msg_player_info = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"msg_game_notice", Value=4)]
      msg_game_notice = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"msg_srequest", Value=5)]
      msg_srequest = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"msg_crequest", Value=6)]
      msg_crequest = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"msg_lobby_start_game", Value=7)]
      msg_lobby_start_game = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"msg_notify_players_loading", Value=8)]
      msg_notify_players_loading = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"msg_notify_players_ready", Value=9)]
      msg_notify_players_ready = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"msg_map_data", Value=10)]
      msg_map_data = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"msg_ent_data", Value=11)]
      msg_ent_data = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"msg_fov_data", Value=12)]
      msg_fov_data = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"msg_player_move", Value=13)]
      msg_player_move = 13,
            
      [global::ProtoBuf.ProtoEnum(Name=@"msg_player_pos", Value=14)]
      msg_player_pos = 14
    }
  
}